<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.243" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2024-08-02T08:37:08" tests="0" file="cypress\e2e\api\api.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="API Test using plugin cypress-plugin-api" timestamp="2024-08-02T08:37:08" tests="1" time="1.206" failures="1">
    <testcase name="API Test using plugin cypress-plugin-api test api - GET " time="0.000" classname="test api - GET ">
      <failure message="`cy.request()` failed trying to load:

https://reqres.in/api/users?page=2

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: getaddrinfo ENOTFOUND reqres.in

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://reqres.in/api/users?page=2

-----------------------------------------------------------

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` failed trying to load:

https://reqres.in/api/users?page=2

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: getaddrinfo ENOTFOUND reqres.in

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://reqres.in/api/users?page=2

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request
    at <unknown> (http://localhost:3184/__cypress/runner/cypress_runner.js:133578:70)
    at tryCatcher (http://localhost:3184/__cypress/runner/cypress_runner.js:1807:23)
    at <unknown> (http://localhost:3184/__cypress/runner/cypress_runner.js:4203:37)
    at tryCatcher (http://localhost:3184/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3184/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3184/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3184/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3184/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:3184/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:3184/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:3184/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:3184/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.ee (webpack:///./node_modules/cypress-plugin-api/dist/support.js:14:2002)

From Node.js Internals:
  RequestError: Error: getaddrinfo ENOTFOUND reqres.in
      at new r (<embedded>:1831:405792)
      at ee.callback (<embedded>:1831:411793)
      at e.callback.s.callback [as _callback] (<embedded>:1831:411239)
      at s._callback.s.callback.s.callback (<embedded>:2049:97858)
      at ee.emit (node:events:514:28)
      at ee.onRequestError (<embedded>:2049:106800)
      at ClientRequest.emit (node:events:526:35)
      at TLSSocket.socketErrorListener (node:_http_client:501:9)
      at TLSSocket.emit (node:events:514:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]]></failure>
    </testcase>
  </testsuite>
</testsuites>